// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs94F3qix0mkokyalQH7cmpCajcVGH0eA',
    appId: '1:950725307189:web:3dc3c45eadbf9fa803ba7c',
    messagingSenderId: '950725307189',
    projectId: 'recall-4653e',
    authDomain: 'recall-4653e.firebaseapp.com',
    storageBucket: 'recall-4653e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk-QDLf36INb5zpPvbfc7mFXhl3FaE9PU',
    appId: '1:950725307189:android:720c1e18e27041cd03ba7c',
    messagingSenderId: '950725307189',
    projectId: 'recall-4653e',
    storageBucket: 'recall-4653e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-bGMYTRHw7y0t8y6YFZTWbmTkKHb3slY',
    appId: '1:950725307189:ios:ee6ce12d62f2216403ba7c',
    messagingSenderId: '950725307189',
    projectId: 'recall-4653e',
    storageBucket: 'recall-4653e.firebasestorage.app',
    iosBundleId: 'com.example.recall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-bGMYTRHw7y0t8y6YFZTWbmTkKHb3slY',
    appId: '1:950725307189:ios:ee6ce12d62f2216403ba7c',
    messagingSenderId: '950725307189',
    projectId: 'recall-4653e',
    storageBucket: 'recall-4653e.firebasestorage.app',
    iosBundleId: 'com.example.recall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs94F3qix0mkokyalQH7cmpCajcVGH0eA',
    appId: '1:950725307189:web:4f193153ff1820ab03ba7c',
    messagingSenderId: '950725307189',
    projectId: 'recall-4653e',
    authDomain: 'recall-4653e.firebaseapp.com',
    storageBucket: 'recall-4653e.firebasestorage.app',
  );

}