// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm8V2V7Hp4g5lGfZjvZJw1g2YaUIsWqQs',
    appId: '1:437641752591:web:6b3edad6209b45705f337a',
    messagingSenderId: '437641752591',
    projectId: 'tudu-a4291',
    authDomain: 'tudu-a4291.firebaseapp.com',
    storageBucket: 'tudu-a4291.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfLtGfFMSequO-y48ByZRQyPzq0yI5dww',
    appId: '1:437641752591:android:df5e8ba2cf08bfae5f337a',
    messagingSenderId: '437641752591',
    projectId: 'tudu-a4291',
    storageBucket: 'tudu-a4291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfve8t8ywou5ido22rcgFR2be_HfdjemA',
    appId: '1:437641752591:ios:a97b94c3bf4814195f337a',
    messagingSenderId: '437641752591',
    projectId: 'tudu-a4291',
    storageBucket: 'tudu-a4291.firebasestorage.app',
    iosBundleId: 'com.example.tudu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfve8t8ywou5ido22rcgFR2be_HfdjemA',
    appId: '1:437641752591:ios:a97b94c3bf4814195f337a',
    messagingSenderId: '437641752591',
    projectId: 'tudu-a4291',
    storageBucket: 'tudu-a4291.firebasestorage.app',
    iosBundleId: 'com.example.tudu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm8V2V7Hp4g5lGfZjvZJw1g2YaUIsWqQs',
    appId: '1:437641752591:web:ab1374f93b32ae015f337a',
    messagingSenderId: '437641752591',
    projectId: 'tudu-a4291',
    authDomain: 'tudu-a4291.firebaseapp.com',
    storageBucket: 'tudu-a4291.firebasestorage.app',
  );
}
